theme: jekyll-theme-slate
author: Sri Subathra Devi B
title: Sri Subathra Devi B | Professional Portfolio
# Edit next line, replacing 'techfolios' with your github username
url: "https://subathra19.github.io/"
navbar-links:
  About Me: "aboutme"

#social-network-links:
 ##
 #facebook: "https://www.facebook.com/subathra.devi.773"
  #github: "https://github.com/Subathra19"
  #linkedin: "https://www.linkedin.com/in/sri-subathra-devi-b-50735280/"
  
#share-links-active:
 # twitter: true
  #facebook: true
  #linkedin: true
