theme: jekyll-theme-slate
title: Welcome to My page
author: Sri Subathra Devi B

#social-network-links:
 ##
 #facebook: "https://www.facebook.com/subathra.devi.773"
  #github: "https://github.com/Subathra19"
  #linkedin: "https://www.linkedin.com/in/sri-subathra-devi-b-50735280/"
  
#share-links-active:
 # twitter: true
  #facebook: true
  #linkedin: true
